apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  APP_ENV: test
  MIGRATION_VERSION: "20211103204247"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
#  DATABASE_URL: postgres://user_app:pa$$word@postgres-postgresql.otus.svc.cluster.local/users_db?sslmode=disable
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyX2FwcDpwYSQkd29yZEBwb3N0Z3Jlcy1wb3N0Z3Jlc3FsLm90dXMuc3ZjLmNsdXN0ZXIubG9jYWwvdXNlcnNfZGI/c3NsbW9kZT1kaXNhYmxl
#  GOOSE_DBSTRING: "user=user_app password=pa$$word dbname=users_db host=postgres-postgresql.otus.svc.cluster.local sslmode=disable"
  GOOSE_DBSTRING: dXNlcj11c2VyX2FwcCBwYXNzd29yZD1wYSQkd29yZCBkYm5hbWU9dXNlcnNfZGIgaG9zdD1wb3N0Z3Jlcy1wb3N0Z3Jlc3FsLm90dXMuc3ZjLmNsdXN0ZXIubG9jYWwgc3NsbW9kZT1kaXNhYmxl
