apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service
          image: strider2038/otus-micro-2-user-service
          ports:
            - name: web
              containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: DATABASE_URL
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: APP_ENV
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5
