apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: otus-micro
build:
  artifacts:
    - image: strider2038/otus-micro-2-user-service
      context: .
      docker:
        dockerfile: build/package/user-service/Dockerfile
        buildArgs:
          APP_VERSION: local
    - image: strider2038/otus-micro-2-user-migrations
      context: .
      docker:
        dockerfile: build/package/migrations/Dockerfile
    - image: strider2038/otus-micro-2-db-waiter
      context: .
      docker:
        dockerfile: build/package/db-waiter/Dockerfile
deploy:
  kubectl:
    defaultNamespace: otus
    manifests:
      - deployments/config.yaml
      - deployments/migrations.yaml
      - deployments/deployment.yaml
      - deployments/ingress.yaml
      - deployments/service.yaml
  helm:
    releases:
      - name: "postgres"
        namespace: "otus"
        remoteChart: "postgresql"
        repo: 'https://charts.bitnami.com/bitnami'
        wait: true
        valuesFiles:
          - deployments/postgres/values.yaml
